#install required packages and load them
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DESeq2",update=FALSE)
BiocManager::install("clusterProfiler",update=FALSE)
BiocManager::install("ggplot2",update=FALSE)
BiocManager::install("magrittr",update=FALSE)
BiocManager::install("stringr",update=FALSE)
BiocManager::install("data.table",update=FALSE)
BiocManager::install("ggsci",update=FALSE)
BiocManager::install("org.Hs.eg.db",update=FALSE)
BiocManager::install("AnnotationDbi",update=FALSE)
BiocManager::install("pheatmap",update=FALSE)
BiocManager::install("RColorBrewer",update=FALSE)
